### PR TITLE
fixes #36 : added development section explaining how to get things go…

### LINKED ISSUE #36: How to do development? (In Readme)
I had problems to clone this project correctly inside Android Studio and build it without errors.
In the Readme there should be a section explaining how to develop the code (for others).

### PR DESCRIPTION
**Pull request by geniusupgrader**
…ing inside Android Studio and build it without errors

### CODE REVIEW

**Comment by brodeurlv** [comment]
Hi, 

Thank you for all those explanations.

One remark more on me in fact : 
I have never be really satisfied with the signingConfigs part of the build.gradle. 
I think I should provide a build.gradle without this constraints and something that doesn't disclose the password.  
I have found this that might be helpful : 
[signing-open-source-android-apps-without-disclosing-passwords](https://www.thoughtworks.com/insights/blog/signing-open-source-android-apps-without-disclosing-passwords)

I will work on this and let you know. 

 Thank you.

**Comment by geniusupgrader** [comment]
I've tested it and you always must rename the release.properties.sample to release.properties. Otherwise no gradle sync can be done, this is my error:

/run/media/robin/ssd2/software/fastnfitness/release.properties (No such file or directory)

So neither (release or debug) can be build, when the gradle sync fails. You always need to rename it.

Is this the intended behaviour  @brodeurlv ? If yes, then I will update the Readme accordingly, that you always must rename the file.

**Comment by brodeurlv** [comment]
Hi @geniusupgrader , no it was not my intent. 
I updated it again and again end I finally succeed to make it work, (I think) as expected.
So if you have a file called "release.properties" or "debug.properties" it will use it, else it won't, without any error.
I hope this one is the good one now. 
Thanks.

**Comment by geniusupgrader** [comment]
Will check this again and update Readme tomorrow

**Comment by geniusupgrader** [comment]
Sorry, I get this:
```Cannot convert URL 'C:/Dev/fastnfitness_keystore/keystore' to a file.```

When I comment the lines out with this URL, then I can build succesfully, but when I try to run it:
```Password verification failed```

**Comment by brodeurlv** [comment]
This is strange. This String 'C:/Dev/fastnfitness_keystore/keystore' is nowhere in the files committed to Git. 
Did you make a "Clean Project" and then a "Build Project" (not a Rebuild) ? 
I had some difficulties due to this yesterday. 

Did you delete your "release.properties" files ? The properties in this files should be without quotes ' " '. 

Thanks.

**Comment by geniusupgrader** [comment]
Sorry, my fault I've done:
```
git fetch --all
git reset --hard origin/master
```

instead of the correct:
```
git fetch --all
git reset --hard upstream/master
```

All is working now and I've updated the readme.

**Comment by brodeurlv** [comment]
Excellent. Thank you.

**Pull request merged**
