### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by brodeurlv** [comment]
Hey, nice job @rffontenelle  !
Thank you. 
I hope I can count on you on future updates to continue the translation ! :)
Thanks

**Comment by rffontenelle** [comment]
Sure, I'll be monitoring `values/strings.xml` for updates. Thanks for merging it.

**Comment by brodeurlv** [comment]
I don't know why, but I had to rename the folder to "values-pt-rBR" instead of "values-pt-BR" .
I will publish the new version tonight on the google play.

**Comment by rffontenelle** [comment]
Thanks for letting me know and sorry for the breakable.  How did you figure out the "r" missing?

**Comment by brodeurlv** [comment]
It did not compile so I looked on Google to figure out why! 😊

**Pull request merged**
