### PR TITLE
Timezone fixes

### LINKED ISSUE #170: Wrong date in history
**Describe your issue**
Hello, 

the current local date and time is 2020-08-14 00:08 . When entering an exercise, it is added for 2020-08-*13* 00:08.

Thank you. 
Your name

**To Reproduce**
1. Go to a 'Program' and start it around midnight.
2. Finish some exercises
3. Finish the program
4. Go to history

**Expected behavior**
Date and time of the exercise in history should be the same as the actual entering time.

**App Version:**
 - Version 0.19.3

**Additional context**
I'm not completely sure about the midnight part. Could also be a coincidence. 

This may be related to #168

### PR DESCRIPTION
**Pull request by ChrisJAllan**
Changes:

* Combines record date and time, fixes issue when local date is different from GMT date
* Date-only objects, such as body recordings, birthday, etc, are always treated as local date, no timezone conversion
* All date and time inputs and outputs use locale strings, follow system preferences on 12/24 hour
* History date filtering uses local time, records sorted by date and time
* All graphs use local time for dates

Fixes #170

### CODE REVIEW

**Review by brodeurlv — APPROVED** [review]
Good for me. Thank you.

**Comment by brodeurlv** [comment]
Hi Chris, 

First thank you for you investment on this open source app. 
I made some tests this weekend on your branch and I'm facing an issue with the graphs that are one day late. 
If you look at the captures below, you will see that on the Free session tab, the time is good (Sept 6) but on the graph tab, the time is wrong (Sept 5 instead of Sept 6). 

Capture1

Capture2

Maybe it is something linked to the fact that graphs are on days only and "cut the time". 

I see the same behavior on all the graphs (workout, boby weight and body measures).

I'd appreciate if you could have look. 
Thank you very much.

Charles

**Comment by ChrisJAllan** [comment]
It seems to be an issue with combining `Date.getTime` and `DateConverter.nbDays`, it always gets the number of days in GMT.

**Comment by ChrisJAllan** [comment]
Should be fixed now.

**Review by brodeurlv — APPROVED** [review]
Good catch !

**Comment by brodeurlv** [comment]
You last commit fixed the issue. 
Thank you Chris for the great work and the support. I'm merging the pull request right away.

**Pull request merged**
