### PR TITLE
Progress images

### PR DESCRIPTION
**Pull request by FirstWithThisName**
Add Progress images, Export and import can done via ZIP-Files.
See https://github.com/brodeurlv/fastnfitness/issues/177

### CODE REVIEW

**Comment by FirstWithThisName** [comment]
I think some cleanup could be done in the ImageUtil class.
But I am uncertain if this the right place to do it.

**Comment by FirstWithThisName** [comment]
@brodeurlv do you have any feedback for me?

**Comment by brodeurlv** [comment]
Hi, I don't forget you. I have currently issues with compiling with the new
android studio. As soon as I can get it working I'll look at your PR.
Thanks.

**Review by brodeurlv — CHANGES_REQUESTED** [review]
Thank you for the PR. The code is clear and respect the current architecture. The import/export feature is also working well.
In term of features, I think only one usability feature is missing to make it complete: 
- Possibility to change the date as you might want to import old pictures of yourself
Nice to have: 
For this kind of feature, I would rather see a swipping on the picture part rather than buttons "newer/older".
And finally, I don't know if this is only me or not but the camera button doesn't launch the camera activity. DO you have the same issue on your side ?

Thank you @FirstWithThisName for the good work.

**Comment by FirstWithThisName** [comment]
After just recompiling and installing I got the camera issue as well.

**Comment by FirstWithThisName** [comment]
Ok, the oldest version I can compile ba96637aab7b319da20e1665ffbe476d7d87db2a has the issue as well.  
So i think it is not an issue of the stream copying, but I am uncertain what the problem is I don't get usefull error messages.  
@brodeurlv do you got an idea what the problem might be?

**Comment by brodeurlv** [comment]
Hi @FirstWithThisName , sorry for the delayed answer. I guess it is a incompatibility issue between the crop-image and the android version. We would need to migrate it to the latests versions of the library.

**Pull request merged**
